name: qyro
description: Cross-platform interface baseline for Qyro.
publish_to: none
version: 0.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  branding_generator:
    path: ../../tools/branding_generator
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/brand/qyro-logo.png
    - assets/generated/logo_ascii.json
