//! Interoperable frame-AEAD vectors: generation, verification and schema.
//!
//! Same reasoning as the handshake vectors, and the same three jobs. A Rust test
//! that seals a frame and opens it again proves that Rust agrees with Rust; it
//! does not show the format is unambiguous, and it is no help to someone writing
//! the Swift or Kotlin side.
//!
//! 1. **Generates** `docs/security/test-vectors/aead-v1.json` deterministically,
//!    from the same seeds and entropy as the committed handshake vector, so the
//!    two files are one chain: the traffic secrets this file expands are the
//!    ones that file records.
//! 2. **Checks** that regenerating reproduces the committed file byte for byte.
//! 3. **Verifies** every recorded value again from the primitives — HKDF-SHA256
//!    and ChaCha20-Poly1305 — without going through [`FrameSealer`]. If the
//!    sealer and the specification disagree, that is where it shows.
//!
//! There is a fourth file involved and it is not generated by anything here:
//! `rfc8439-chacha20poly1305.json` holds the RFC's own vectors, transcribed from
//! the RFC text. It pins the primitive; this file pins what Qyro does with it.

use chacha20poly1305::{AeadInOut, ChaCha20Poly1305, KeyInit};
use hkdf::Hkdf;
use qyro_protocol::{DecodedFrame, Flags, Frame, FrameDecoder, HEADER_LEN, MessageType, SessionId};
use serde_json::{Value, json};
use sha2::Sha256;

use super::{
    AEAD_KEY_LEN, FrameOpener, FrameSealer, NONCE_LEN, NONCE_PREFIX_LEN, REPLAY_WINDOW, TAG_LEN,
};
use crate::handshake::{InitiatorStart, ResponderStart};
use crate::identity::DeviceIdentity;
use crate::schema::validate;

/// The committed vectors.
const COMMITTED: &str = include_str!("../../../../../docs/security/test-vectors/aead-v1.json");

/// The schema the committed vectors must satisfy.
const SCHEMA: &str = include_str!("../../../../../docs/security/test-vectors/aead-v1.schema.json");

/// The handshake vectors this file chains to.
const HANDSHAKE: &str = include_str!("../../../../../docs/security/test-vectors/handshake-v1.json");

/// The RFC's own vectors for the primitive underneath all of this.
const RFC8439: &str =
    include_str!("../../../../../docs/security/test-vectors/rfc8439-chacha20poly1305.json");

// TEST ONLY — NEVER PRODUCTION. The same values the handshake vector uses; that
// is what makes the two files one chain rather than two unrelated documents.
const INITIATOR_SEED: [u8; 32] = [0x11; 32];
const RESPONDER_SEED: [u8; 32] = [0x22; 32];

/// Deterministic handshake entropy. TEST ONLY — NEVER PRODUCTION.
fn entropy(tag: u8) -> [u8; 64] {
    let mut out = [0u8; 64];
    for (index, slot) in out.iter_mut().enumerate() {
        *slot = tag ^ (index as u8).wrapping_mul(31).wrapping_add(7);
    }
    out
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

fn unhex(text: &str) -> Vec<u8> {
    assert!(text.len().is_multiple_of(2), "hex must be byte-aligned");
    assert!(
        text.bytes()
            .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase()),
        "vectors use lowercase hex only"
    );
    (0..text.len())
        .step_by(2)
        .map(|index| u8::from_str_radix(&text[index..index + 2], 16).expect("hex digit"))
        .collect()
}

/// One frame the vector file records, before it is sealed.
struct Plan {
    name: &'static str,
    message_type: MessageType,
    flags: Flags,
    transfer_id: u64,
    stream_id: u32,
    item_id: u32,
    payload: Vec<u8>,
}

/// What the initiator sends. Chosen to move every field the AAD covers.
fn initiator_plan() -> Vec<Plan> {
    vec![
        Plan {
            name: "empty payload, no flags, sequence zero",
            message_type: MessageType::DataChunk,
            flags: Flags::NONE,
            transfer_id: 0,
            stream_id: 0,
            item_id: 0,
            payload: Vec::new(),
        },
        Plan {
            name: "short payload, identifiers set",
            message_type: MessageType::DataChunk,
            flags: Flags::NONE,
            transfer_id: 0x0102_0304_0506_0708,
            stream_id: 0x090a_0b0c,
            item_id: 0x0d0e_0f10,
            payload: b"qyro".to_vec(),
        },
        Plan {
            name: "both transport flags, a different message type",
            message_type: MessageType::ItemStart,
            flags: Flags::END_OF_ITEM.union(Flags::END_OF_TRANSFER),
            transfer_id: u64::MAX,
            stream_id: u32::MAX,
            item_id: u32::MAX,
            payload: (0u8..=255).collect(),
        },
    ]
}

/// What the responder sends, on its own key, prefix and counter.
fn responder_plan() -> Vec<Plan> {
    vec![
        Plan {
            name: "acknowledgement, sequence zero of the other direction",
            message_type: MessageType::ChunkAck,
            flags: Flags::NONE,
            transfer_id: 0x0102_0304_0506_0708,
            stream_id: 0x090a_0b0c,
            item_id: 0x0d0e_0f10,
            payload: vec![0x00, 0x01, 0x02, 0x03],
        },
        Plan {
            name: "completion, one transport flag",
            message_type: MessageType::Complete,
            flags: Flags::END_OF_TRANSFER,
            transfer_id: 0x0102_0304_0506_0708,
            stream_id: 0,
            item_id: 0,
            payload: b"done".to_vec(),
        },
    ]
}

impl Plan {
    fn frame(&self) -> Frame {
        Frame::new(self.message_type, self.payload.clone())
            .expect("within limits")
            .with_flags(self.flags)
            .expect("transport flags only")
            // The session identifier here is deliberately wrong; the sealer
            // overwrites it, and the recorded header shows that it did.
            .with_identifiers(
                SessionId::ZERO,
                self.transfer_id,
                self.stream_id,
                self.item_id,
            )
    }
}

/// Everything one run produces.
struct Recorded {
    session_id: SessionId,
    auth_transcript: [u8; 32],
    initiator_to_responder_secret: [u8; 32],
    responder_to_initiator_secret: [u8; 32],
    initiator_sealer: FrameSealer,
    initiator_opener: FrameOpener,
    responder_sealer: FrameSealer,
    responder_opener: FrameOpener,
}

/// Runs the handshake the ordinary way and derives the frame crypto from it.
fn run() -> Recorded {
    let initiator = DeviceIdentity::from_test_seed(&INITIATOR_SEED);
    let responder = DeviceIdentity::from_test_seed(&RESPONDER_SEED);

    let (initiator_hello, awaiting_responder) = InitiatorStart::new(&initiator)
        .send_hello_with_entropy(entropy(0xA0))
        .expect("opens");
    let (responder_hello, awaiting_initiator_finish) = ResponderStart::new(&responder)
        .receive_initiator_hello(&initiator_hello, entropy(0xB0))
        .expect("accepts");
    let (initiator_finish, awaiting_responder_finish) = awaiting_responder
        .receive_responder_hello(&responder_hello)
        .expect("verifies");
    let pending = awaiting_initiator_finish
        .receive_initiator_finish(&initiator_finish)
        .expect("verifies");
    let responder_finish = *pending.encoded_finish();
    let established_responder = pending.confirm_sent();
    let established_initiator = awaiting_responder_finish
        .receive_responder_finish(&responder_finish)
        .expect("verifies");

    let session_id = established_initiator.session_id();
    let auth_transcript = established_initiator.auth_transcript_for_test();
    let initiator_to_responder_secret = *established_initiator.sending_key_bytes();
    let responder_to_initiator_secret = *established_initiator.receiving_key_bytes();

    let (initiator_sealer, initiator_opener) = established_initiator
        .into_frame_crypto()
        .expect("derives the initiator's frame crypto");
    let (responder_sealer, responder_opener) = established_responder
        .into_frame_crypto()
        .expect("derives the responder's frame crypto");

    Recorded {
        session_id,
        auth_transcript,
        initiator_to_responder_secret,
        responder_to_initiator_secret,
        initiator_sealer,
        initiator_opener,
        responder_sealer,
        responder_opener,
    }
}

/// Rebuilds the HKDF `info` for one label, exactly as ADR-0022 specifies.
///
/// Written out here from the ADR rather than calling `super::info_for`, so the
/// file records the specification and not this implementation's reading of it.
fn info_for(direction: &str, purpose: &str, auth: &[u8; 32], session: SessionId) -> Vec<u8> {
    let mut info = Vec::new();
    info.extend_from_slice(b"QYRO-AEAD-V1/");
    info.extend_from_slice(direction.as_bytes());
    info.push(b'/');
    info.extend_from_slice(purpose.as_bytes());
    info.push(0x00);
    info.extend_from_slice(auth);
    info.extend_from_slice(session.as_bytes());
    info
}

/// Expands one traffic secret to `N` bytes under one label, using HKDF directly.
fn expand<const N: usize>(secret: &[u8; 32], info: &[u8]) -> [u8; N] {
    let hkdf = Hkdf::<Sha256>::from_prk(secret).expect("a 32-byte PRK");
    let mut out = [0u8; N];
    hkdf.expand(info, &mut out).expect("a supported length");
    out
}

/// The derivation block for one direction, computed from primitives.
fn derivation(secret: &[u8; 32], direction: &str, auth: &[u8; 32], session: SessionId) -> Value {
    let info_key = info_for(direction, "key", auth, session);
    let info_nonce_prefix = info_for(direction, "nonce-prefix", auth, session);
    json!({
        "info_key": hex(&info_key),
        "info_nonce_prefix": hex(&info_nonce_prefix),
        "aead_key": hex(&expand::<AEAD_KEY_LEN>(secret, &info_key)),
        "nonce_prefix": hex(&expand::<NONCE_PREFIX_LEN>(secret, &info_nonce_prefix)),
    })
}

/// Seals one plan and records everything an implementer needs to reproduce it.
fn seal_and_record(sealer: &mut FrameSealer, plan: &Plan) -> Value {
    let sealed = sealer.seal(&plan.frame()).expect("seals");
    let envelope = sealed.envelope();
    let header = envelope.header();
    json!({
        "name": plan.name,
        "message_type": header.message_type().to_wire(),
        "flags": header.flags().bits(),
        "transfer_id": hex(&header.transfer_id().to_be_bytes()),
        "stream_id": hex(&header.stream_id().to_be_bytes()),
        "item_id": hex(&header.item_id().to_be_bytes()),
        "sequence": hex(&header.sequence().to_be_bytes()),
        "nonce": hex(&sealed.nonce()),
        "associated_data": hex(&envelope.associated_data()),
        "plaintext": hex(&plan.payload),
        "ciphertext": hex(envelope.ciphertext()),
        "tag": hex(envelope.tag()),
        "frame": hex(&sealed.encode()),
    })
}

/// Builds the vector document.
fn build_document() -> Value {
    let mut recorded = run();
    let session = recorded.session_id;
    let auth = recorded.auth_transcript;

    let initiator_frames: Vec<Value> = initiator_plan()
        .iter()
        .map(|plan| seal_and_record(&mut recorded.initiator_sealer, plan))
        .collect();
    let responder_frames: Vec<Value> = responder_plan()
        .iter()
        .map(|plan| seal_and_record(&mut recorded.responder_sealer, plan))
        .collect();

    json!({
        "_warning": "TEST ONLY - NEVER PRODUCTION. Every key and secret below is derived from published seeds and is therefore compromised by definition.",
        "format": "qyro-aead-v1",
        "specification": "docs/adr/ADR-0022-qyro1-frame-aead.md",
        "aead_algorithm": "ChaCha20-Poly1305, RFC 8439",
        "chained_from": "handshake-v1.json",
        "note": "The session below is the one handshake-v1.json records, run from the same seeds and the same entropy. Its traffic secrets are the input to the derivation here, so an implementation can verify the handshake first and continue straight into the frame layer. Associated data is the whole 48-byte header; altering any byte of it invalidates the tag.",
        "suite": {
            "aead_key_len": AEAD_KEY_LEN,
            "nonce_len": NONCE_LEN,
            "nonce_prefix_len": NONCE_PREFIX_LEN,
            "tag_len": TAG_LEN,
            "header_len": HEADER_LEN,
            "replay_window": REPLAY_WINDOW,
        },
        "session": {
            "session_id": hex(session.as_bytes()),
            "auth_transcript_hash": hex(&auth),
            "initiator_to_responder_traffic_secret": hex(&recorded.initiator_to_responder_secret),
            "responder_to_initiator_traffic_secret": hex(&recorded.responder_to_initiator_secret),
        },
        "derivation": {
            "initiator_to_responder": derivation(
                &recorded.initiator_to_responder_secret, "i2r", &auth, session),
            "responder_to_initiator": derivation(
                &recorded.responder_to_initiator_secret, "r2i", &auth, session),
        },
        "initiator_to_responder_frames": initiator_frames,
        "responder_to_initiator_frames": responder_frames,
    })
}

/// Renders the document exactly as the committed file stores it.
fn render(document: &Value) -> String {
    let mut text = serde_json::to_string_pretty(document).expect("serializable");
    text.push('\n');
    text
}

// ---------------------------------------------------------------- generation

/// Prints the vector file. **Not run by default.**
///
/// ```text
/// cargo test -p qyro_crypto generate_aead_vector -- --ignored --nocapture
/// ```
#[test]
#[ignore = "regenerates the committed vector file; run explicitly"]
fn generate_aead_vector() {
    print!("{}", render(&build_document()));
}

#[test]
fn the_committed_vector_is_exactly_what_regeneration_produces() {
    let regenerated = render(&build_document());
    assert_eq!(
        regenerated, COMMITTED,
        "the committed AEAD vector is stale; regenerate it with \
         `cargo test -p qyro_crypto generate_aead_vector -- --ignored --nocapture`"
    );
}

#[test]
fn the_vector_chains_to_the_committed_handshake_vector() {
    // The claim `chained_from` makes, checked rather than asserted in prose. If
    // either file is regenerated from different seeds, this is what notices.
    let aead: Value = serde_json::from_str(COMMITTED).expect("valid JSON");
    let handshake: Value = serde_json::from_str(HANDSHAKE).expect("valid JSON");

    for (aead_path, handshake_path) in [
        (["session", "session_id"], ["schedule", "session_id"]),
        (
            ["session", "auth_transcript_hash"],
            ["transcript", "auth_transcript_hash"],
        ),
        (
            ["session", "initiator_to_responder_traffic_secret"],
            ["schedule", "initiator_to_responder_traffic_secret"],
        ),
        (
            ["session", "responder_to_initiator_traffic_secret"],
            ["schedule", "responder_to_initiator_traffic_secret"],
        ),
    ] {
        assert_eq!(
            aead[aead_path[0]][aead_path[1]], handshake[handshake_path[0]][handshake_path[1]],
            "{aead_path:?} must be the value handshake-v1.json records at {handshake_path:?}"
        );
    }
}

// -------------------------------------------------------------------- schema

#[test]
fn the_committed_vector_satisfies_the_schema() {
    let document: Value = serde_json::from_str(COMMITTED).expect("the vector file is valid JSON");
    let schema: Value = serde_json::from_str(SCHEMA).expect("the schema is valid JSON");
    validate(&document, &schema, "").expect("the committed vector satisfies its schema");
}

#[test]
fn the_schema_rejects_what_it_says_it_rejects() {
    let schema: Value = serde_json::from_str(SCHEMA).expect("valid JSON");
    let original: Value = serde_json::from_str(COMMITTED).expect("valid JSON");

    // A tag of the wrong width. Sixteen bytes is the suite; anything else is a
    // different algorithm wearing the same name.
    let mut short_tag = original.clone();
    short_tag["initiator_to_responder_frames"][0]["tag"] = json!("00112233");
    assert!(validate(&short_tag, &schema, "").is_err(), "short tag");

    // A truncated session id: eight bytes is the wire width.
    let mut truncated = original.clone();
    truncated["session"]["session_id"] = json!("00112233");
    assert!(
        validate(&truncated, &schema, "").is_err(),
        "short session id"
    );

    // Associated data that is not a whole header.
    let mut short_aad = original.clone();
    short_aad["initiator_to_responder_frames"][0]["associated_data"] = json!("0011");
    assert!(validate(&short_aad, &schema, "").is_err(), "short header");

    // Uppercase hex: one value, one spelling.
    let mut uppercase = original.clone();
    uppercase["session"]["session_id"] = json!(
        original["session"]["session_id"]
            .as_str()
            .expect("string")
            .to_uppercase()
    );
    assert!(validate(&uppercase, &schema, "").is_err(), "uppercase hex");

    // An empty frame list satisfies every other rule and proves nothing.
    let mut empty = original.clone();
    empty["initiator_to_responder_frames"] = json!([]);
    assert!(validate(&empty, &schema, "").is_err(), "no frames");

    // An unknown property, and a missing one.
    let mut extra = original.clone();
    extra["session"]["surprise"] = json!("00");
    assert!(validate(&extra, &schema, "").is_err(), "unknown property");

    let mut missing = original.clone();
    missing["session"]
        .as_object_mut()
        .expect("object")
        .remove("session_id");
    assert!(validate(&missing, &schema, "").is_err(), "missing property");

    // A changed suite constant.
    let mut suite = original.clone();
    suite["suite"]["tag_len"] = json!(24);
    assert!(validate(&suite, &schema, "").is_err(), "wrong tag length");

    // And the untouched document still passes, so the checks above are
    // rejecting the mutation rather than the document.
    assert!(validate(&original, &schema, "").is_ok());
}

// -------------------------------------------------- independent verification

/// Reads a nested string field out of a document.
fn field(document: &Value, path: &[&str]) -> String {
    let mut node = document;
    for key in path {
        node = &node[*key];
    }
    node.as_str()
        .unwrap_or_else(|| panic!("{path:?} is a string"))
        .to_owned()
}

fn fixed<const N: usize>(document: &Value, path: &[&str]) -> [u8; N] {
    unhex(&field(document, path))
        .try_into()
        .unwrap_or_else(|_| panic!("{path:?} is {N} bytes"))
}

#[test]
fn every_recorded_value_verifies_against_the_primitives() {
    // Rebuilds each derived value and each tag from HKDF and ChaCha20-Poly1305
    // directly. Nothing here calls FrameSealer, so a change in the sealer that
    // also changed the vectors would still be caught: the file would stop
    // matching the specification even while matching the code.
    let document: Value = serde_json::from_str(COMMITTED).expect("valid JSON");

    let session_id: [u8; 8] = fixed(&document, &["session", "session_id"]);
    let session = SessionId::from_be_bytes(session_id);
    let auth: [u8; 32] = fixed(&document, &["session", "auth_transcript_hash"]);

    for (direction, secret_field, frames_field) in [
        (
            "i2r",
            "initiator_to_responder_traffic_secret",
            "initiator_to_responder_frames",
        ),
        (
            "r2i",
            "responder_to_initiator_traffic_secret",
            "responder_to_initiator_frames",
        ),
    ] {
        let block = if direction == "i2r" {
            "initiator_to_responder"
        } else {
            "responder_to_initiator"
        };
        let secret: [u8; 32] = fixed(&document, &["session", secret_field]);

        // --- derivation -----------------------------------------------------
        let info_key = info_for(direction, "key", &auth, session);
        let info_prefix = info_for(direction, "nonce-prefix", &auth, session);
        assert_eq!(
            hex(&info_key),
            field(&document, &["derivation", block, "info_key"]),
            "{direction}: the recorded key label is label || 0x00 || transcript || session"
        );
        assert_eq!(
            hex(&info_prefix),
            field(&document, &["derivation", block, "info_nonce_prefix"])
        );

        let key = expand::<AEAD_KEY_LEN>(&secret, &info_key);
        let prefix = expand::<NONCE_PREFIX_LEN>(&secret, &info_prefix);
        assert_eq!(
            hex(&key),
            field(&document, &["derivation", block, "aead_key"]),
            "{direction}: the recorded key is HKDF-Expand over the traffic secret"
        );
        assert_eq!(
            hex(&prefix),
            field(&document, &["derivation", block, "nonce_prefix"])
        );

        // --- frames ---------------------------------------------------------
        let frames = document[frames_field].as_array().expect("an array");
        assert!(!frames.is_empty(), "{direction}: frames are recorded");

        for (index, frame) in frames.iter().enumerate() {
            let sequence: [u8; 8] = fixed(frame, &["sequence"]);
            assert_eq!(
                u64::from_be_bytes(sequence),
                index as u64,
                "{direction}: sequences start at zero and increase by one"
            );

            let mut expected_nonce = [0u8; NONCE_LEN];
            expected_nonce[..NONCE_PREFIX_LEN].copy_from_slice(&prefix);
            expected_nonce[NONCE_PREFIX_LEN..].copy_from_slice(&sequence);
            assert_eq!(
                hex(&expected_nonce),
                field(frame, &["nonce"]),
                "{direction} frame {index}: the nonce is prefix || sequence"
            );

            let associated_data = unhex(&field(frame, &["associated_data"]));
            assert_eq!(
                associated_data.len(),
                HEADER_LEN,
                "the associated data is the whole header"
            );
            assert_eq!(
                &associated_data[16..24],
                &session_id[..],
                "the sealer stamped the session id into the header"
            );
            assert_eq!(&associated_data[40..48], &sequence[..]);

            let bytes = unhex(&field(frame, &["frame"]));
            assert_eq!(
                &bytes[..HEADER_LEN],
                &associated_data[..],
                "{direction} frame {index}: the header on the wire is the authenticated one"
            );

            let mut buffer = unhex(&field(frame, &["plaintext"]));
            let tag = ChaCha20Poly1305::new_from_slice(&key)
                .expect("a 32-byte key")
                .encrypt_inout_detached(
                    &expected_nonce.into(),
                    &associated_data,
                    buffer.as_mut_slice().into(),
                )
                .expect("seals");

            assert_eq!(
                hex(&buffer),
                field(frame, &["ciphertext"]),
                "{direction} frame {index}: ChaCha20-Poly1305 reproduces the ciphertext"
            );
            assert_eq!(
                hex(&tag),
                field(frame, &["tag"]),
                "{direction} frame {index}: and the tag"
            );
            assert_eq!(
                bytes,
                [&associated_data[..], &buffer[..], tag.as_slice()].concat(),
                "{direction} frame {index}: the frame is header || ciphertext || tag"
            );
        }
    }
}

#[test]
fn the_recorded_frames_open_through_the_decoder_and_the_opener() {
    // The other direction of the same claim: the bytes in the file are bytes an
    // ordinary receiver accepts, not just bytes this crate can regenerate.
    let document: Value = serde_json::from_str(COMMITTED).expect("valid JSON");
    let mut recorded = run();

    // The openers come from `into_frame_crypto`, not from hand-wired secrets.
    // Pairing them by hand is exactly the mistake this test exists to catch, and
    // the first draft of it made that mistake: it fed each opener the secret for
    // the direction it does not read, and every recorded frame failed to open.
    for (frames_field, opener) in [
        (
            "initiator_to_responder_frames",
            &mut recorded.responder_opener,
        ),
        (
            "responder_to_initiator_frames",
            &mut recorded.initiator_opener,
        ),
    ] {
        for frame in document[frames_field].as_array().expect("an array") {
            let bytes = unhex(&field(frame, &["frame"]));

            let mut decoder = FrameDecoder::new();
            decoder.push(&bytes).expect("within buffer");
            let envelope = match decoder.next_frame() {
                Ok(Some(DecodedFrame::Encrypted(envelope))) => envelope,
                other => panic!("a recorded frame decodes as an envelope, got {other:?}"),
            };

            let opened = opener.open(&envelope).expect("the recorded frame opens");
            assert_eq!(hex(opened.payload()), field(frame, &["plaintext"]));

            // And it opens exactly once.
            assert!(
                opener.open(&envelope).is_err(),
                "a recorded frame is not a licence to replay it"
            );
        }
    }
}

// -------------------------------------------------------------- the RFC below

#[test]
fn the_chacha20poly1305_implementation_matches_rfc8439() {
    // The primitive, pinned against the RFC's own numbers rather than against
    // anything this repository produced. Both cases run in both directions: the
    // encryption vector is decrypted again and the decryption vector is
    // re-encrypted, so neither half is taken on trust.
    let document: Value = serde_json::from_str(RFC8439).expect("valid JSON");
    let cases = document["cases"].as_array().expect("an array of cases");
    assert_eq!(cases.len(), 2, "section 2.8.2 and appendix A.5");

    for case in cases {
        let name = field(case, &["name"]);
        let key = unhex(&field(case, &["key"]));
        let nonce: [u8; NONCE_LEN] = fixed(case, &["nonce"]);
        let associated_data = unhex(&field(case, &["associated_data"]));
        let plaintext = unhex(&field(case, &["plaintext"]));
        let expected_ciphertext = unhex(&field(case, &["ciphertext"]));
        let expected_tag = unhex(&field(case, &["tag"]));

        let cipher = ChaCha20Poly1305::new_from_slice(&key).expect("a 32-byte key");

        let mut buffer = plaintext.clone();
        let tag = cipher
            .encrypt_inout_detached(
                &nonce.into(),
                &associated_data,
                buffer.as_mut_slice().into(),
            )
            .expect("seals");
        assert_eq!(buffer, expected_ciphertext, "{name}: ciphertext");
        assert_eq!(tag.as_slice(), expected_tag, "{name}: tag");

        let mut buffer = expected_ciphertext.clone();
        let tag: [u8; TAG_LEN] = expected_tag.clone().try_into().expect("a 16-byte tag");
        cipher
            .decrypt_inout_detached(
                &nonce.into(),
                &associated_data,
                buffer.as_mut_slice().into(),
                &tag.into(),
            )
            .unwrap_or_else(|_| panic!("{name}: the RFC's own tag must verify"));
        assert_eq!(buffer, plaintext, "{name}: plaintext");

        // A single flipped bit anywhere must break it.
        for position in [0usize, associated_data.len() - 1] {
            let mut altered = associated_data.clone();
            altered[position] ^= 0x01;
            let mut buffer = expected_ciphertext.clone();
            assert!(
                cipher
                    .decrypt_inout_detached(
                        &nonce.into(),
                        &altered,
                        buffer.as_mut_slice().into(),
                        &tag.into(),
                    )
                    .is_err(),
                "{name}: altered associated data must not verify"
            );
        }
    }
}
